repos:
- hooks:
  - entry: .dvc/tmp/hooks/pre-commit
    id: dvc-pre-commit
    language: script
    name: DVC Pre Commit
    stages:
    - commit
  - entry: .dvc/tmp/hooks/push
    id: dvc-pre-push
    language: script
    name: DVC Pre Push
    stages:
    - push
  - entry: .dvc/tmp/hooks/post-checkout
    id: dvc-post-checkout
    language: script
    name: DVC Post Checkout
    stages:
    - post-checkout
  repo: local
